Document: mylib
Title: Debian mylib Manual
Author: <insert document author here>
Abstract: This manual describes what mylib is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mylib/mylib.sgml.gz

Format: postscript
Files: /usr/share/doc/mylib/mylib.ps.gz

Format: text
Files: /usr/share/doc/mylib/mylib.text.gz

Format: HTML
Index: /usr/share/doc/mylib/html/index.html
Files: /usr/share/doc/mylib/html/*.html
