Document: myapp
Title: Debian myapp Manual
Author: <insert document author here>
Abstract: This manual describes what myapp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/myapp/myapp.sgml.gz

Format: postscript
Files: /usr/share/doc/myapp/myapp.ps.gz

Format: text
Files: /usr/share/doc/myapp/myapp.text.gz

Format: HTML
Index: /usr/share/doc/myapp/html/index.html
Files: /usr/share/doc/myapp/html/*.html
